### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by jwirth-iisys** [arugenre/Charts-DL-SS2024#1]
Script files like validate.py contain imports like

```
from data.common.schemas import Chart
from data.common.utils import convert_json_to_chart_objects
```

but data/commons barely contains anything, at least not the classes and functions referenced.

**Comment by akimikano** [comment]
> Script files like validate.py contain imports like
> 
> ```
> from data.common.schemas import Chart
> from data.common.utils import convert_json_to_chart_objects
> ```
> 
> but data/commons barely contains anything, at least not the classes and functions referenced.

There is one missing file with utility functions, can we upload it?

**Comment by jwirth-iisys** [comment]
Of course, your code cannot be run, if you don't

**Comment by akimikano** [comment]
> Of course, your code cannot be run, if you don't

We have uploaded

**Comment by jwirth-iisys** [comment]
Thanks for the correction.
